apiVersion: pachyderm.dejophus.dev/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: pachyderm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pachyderm-operator
  name: pipeline-sample
spec:
  name: edges
  description: A pipeline that performs image edge detection by using the OpenCV library.
  project: default
  transform:
    image: pachyderm/opencv:1.0
    cmd: ["python3", "/edges.py"]
  input:
    pfs:
      repo: images
      glob: "/*"
