apiVersion: pachyderm.dejophus.dev/v1alpha1
kind: Pachyderm
metadata:
  labels:
    app.kubernetes.io/name: pachyderm
    app.kubernetes.io/instance: pachyderm-sample
    app.kubernetes.io/part-of: pachyderm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pachyderm-operator
  name: pachyderm-sample
spec:
  # TODO(user): Add fields here
